export const physicsChapters = {
  paper1: {
    name: "Paper 1",
    chapters: [
      {
        name: "ENERGY",
        icon: "phy_energy",
        data: [
          { id: "1", subChapter: "Energy Stores and Systems", progress: 70, icon: "phy_energy_store" },
          { id: "2", subChapter: "Kinetic and Potential Energy Stores", progress: 20, icon: "phy_kinetic" },
          { id: "3", subChapter: "Specific Heat Capacity", progress: 20, icon: "phy_specific_heat" },
          { id: "4", subChapter: "Conservation of Energy and Power", progress: 0, icon: "phy_conservation_energy" },
          { id: "5", subChapter: "Conduction and Convection", progress: 0, icon: "phy_conduction" },
          { id: "6", subChapter: "Reducing Unwanted Energy Transfers", progress: 0, icon: "phy_energy_transfers" },
          { id: "7", subChapter: "Efficiency", progress: 0, icon: "phy_efficiency" },
          { id: "8", subChapter: "Energy Resources and Their Uses", progress: 0, icon: "phy_energy_resource" },
          { id: "9", subChapter: "Wind, Solar, and Geothermal", progress: 0, icon: "phy_wind_solar" },
          { id: "10", subChapter: "Hydro-electricity, Waves, and Tides", progress: 0, icon: "phy_hydro" },
          { id: "11", subChapter: "Bio-fuels and Non-renewables", progress: 0, icon: "phy_bio_fuels" },
          { id: "12", subChapter: "Trends in Energy Resource Use", progress: 0, icon: "phy_trends_energy" },
          { id: "13", subChapter: "Revision Questions for Chapter 1", progress: 0, icon: "phy_ques" },
        ],
      },
      {
        name: "ELECTRICITY",
        icon: "phy_electricity",
        data: [
          { id: "1", subChapter: "Current and Circuit Symbols", progress: 0, icon: "phy_current" },
          { id: "2", subChapter: "Resistance and V=IR", progress: 0, icon: "phy_resistanceVIR" },
          { id: "3", subChapter: "Resistance and I-V Characteristics", progress: 0, icon: "phy_resistanceIV" },
          { id: "4", subChapter: "Circuit Devices", progress: 0, icon: "phy_circuit_devices" },
          { id: "5", subChapter: "Series Circuits", progress: 0, icon: "phy_series_circuits" },
          { id: "6", subChapter: "Parallel Circuits", progress: 0, icon: "phy_parallel_circuits" },
          { id: "7", subChapter: "Investigating Resistance", progress: 0, icon: "phy_investigating_resistance" },
          { id: "8", subChapter: "Electricity in the Home", progress: 0, icon: "phy_electricity_home" },
          { id: "9", subChapter: "Power of Electrical Appliances", progress: 0, icon: "phy_power_electrical_appliances" },
          { id: "10", subChapter: "More on Power", progress: 0, icon: "phy_more_power" },
          { id: "11", subChapter: "The National Grid", progress: 0, icon: "phy_the_national_grid" },
          { id: "12", subChapter: "Static Electricity", progress: 0, icon: "phy_static_electricity" },
          { id: "13", subChapter: "Electric Fields", progress: 0, icon: "phy_electric_fields" },
          { id: "14", subChapter: "Revision Questions for Chapter 2", progress: 0, icon: "phy_ques" },
        ],
      },
    ],
  },

  paper2: {
    name: "Paper 2",
    chapters: [
      {
        name: "FORCES",
        icon: "phy_forces",
        data: [
          { id: "1", subChapter: "Contact and Non-contact Forces", progress: 0, icon: "activity" },
          { id: "2", subChapter: "Weight, Mass, and Gravity", progress: 0, icon: "divide-square" },
          { id: "3", subChapter: "Resultant Force and Work Done", progress: 0, icon: "trending-up" },
          { id: "4", subChapter: "Calculating Forces", progress: 0, icon: "cpu" },
          { id: "5", subChapter: "Forces and Elasticity", progress: 0, icon: "git-branch" },
          { id: "6", subChapter: "Investigating Springs", progress: 0, icon: "git-fork" },
          { id: "7", subChapter: "Moments", progress: 0, icon: "search" },
          { id: "8", subChapter: "Fluid Pressure", progress: 0, icon: "home" },
          { id: "9", subChapter: "Upthrust and Atmospheric Pressure", progress: 0, icon: "zap" },
          { id: "10", subChapter: "Distance, Displacement, Speed, and Velocity", progress: 0, icon: "zap-off" },
          { id: "11", subChapter: "Acceleration", progress: 0, icon: "globe" },
          { id: "12", subChapter: "Distance-Time and Velocity-Time Graphs", progress: 0, icon: "cloud-lightning" },
          { id: "13", subChapter: "Terminal Velocity", progress: 0, icon: "rss" },
          { id: "14", subChapter: "Revision Questions for Chapter 1", progress: 0, icon: "file-question" },
        ],
      },
    ],
  },
};
